name: Codex Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build & run Codex pipeline
        run: docker-compose up --build --exit-code-from codex
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}